### ISSUE TITLE
Implement ability to show logs when pushing an application to CF

### ISSUE THREAD

**Issue by xyloman** [nulldriver/cf-cli-resource#19]
Similar to recent support in the concourse cf resource: https://github.com/concourse/cf-resource/commit/b99880e8bc41c25185182fb958314760ea7c3a52

It would be nice to have the ability to show the app logs while an application is pushing to CF in a concourse job.  It appears that the show app log feature was added to auto pilot recently which could then be consumed by cf-cli-resource: https://github.com/contraband/autopilot/commit/aea62a36913e6223d0e7959462981c3bfee0886f

**Comment by patrickcrocker** [comment]
Implemented in [v2.19.0](https://github.com/nulldriver/cf-cli-resource/releases/tag/v2.19.0)!
