### ISSUE TITLE
Restart and Restage are giving an Unknown command error

### ISSUE THREAD

**Issue by dilipmighty245** [nulldriver/cf-cli-resource#33]
Hi,

Im getting the following error when I use "restart" or "restage"

**In my Pipeline.yml file:**

resource_types:
resources:
- name: cf-resource
  type: cf-cli-resource
  source:
    api: https://{myAPI}
    org: platform
    username: username
    password: password
    skip_cert_check: true
    space: Dev
    tag: latest

- name: cf-cli-resource
  type: docker-image
  source:
    repository: nulldriver/cf-cli-resource
    tag: 2.5.1

jobs:
- name: cf-pusher
  serial: true
  plan:
  - put: cf-resource
    params:
      command: restage
      app_name: csl-test-app
      staging_timeout: 15s
      startup_timeout: 5

**ERROR:**
[INFO] cf version 6.35.2+88a03e995.2018-03-15
Setting api endpoint to https://{myAPI}...
OK

api endpoint:   https://{myAPI}
api version:    2.94.0
Not logged in. Use 'cf login' to log in.
API endpoint: https://{myAPI}
Authenticating...
OK
Use 'cf target' to view or set your target org and space.
[ERROR] invalid payload (unknown command: restage)

**Comment by patrickcrocker** [comment]
The `restart` and `restage` commands have not been implemented in `cf-cli-resource` yet.  Please check the [readme](https://github.com/nulldriver/cf-cli-resource/blob/master/README.md) for all the currently supported commands.

I'll add the `restart` and `restage` commands to the backlog (and of course, PRs are always welcome :-)

**Comment by patrickcrocker** [comment]
Implemented in v2.6.0.
