### ISSUE TITLE
mikefarah/yaml version 1.10 not found

### ISSUE THREAD

**Issue by legnoh** [nulldriver/cf-cli-resource#36]
mikefarah/yaml  version 1.10 not found. 
https://github.com/nulldriver/cf-cli-resource/blob/6659a7d16606ab4bbbd3617d3a52f0e70c48c69f/Dockerfile#L20

It was caused by old release removed...
https://github.com/mikefarah/yaml/releases

**Comment by patrickcrocker** [comment]
I'll take a closer look at this later and see if one of the new versions will work.  For now, I copied the v1.10 version of `yaml` from the `cf-cli-resource:2.6.0` docker image to a GCP storage bucket.
