### ISSUE TITLE
Support bind-route-service

### ISSUE THREAD

**Issue by eruvanos** [nulldriver/cf-cli-resource#46]
The tool already supports any kind of service and user-provided-route-service creation. It would be nice also to be able to bind those route-services to a route.

Use case: Use an authentication route service for an application
Steps:
- create route (currently not supported)
- create/update route service (#44 )
- bind-route-service (this PR)
- push/start app 

Regards

**Comment by FlorianSW** [comment]
Totally agree. I'd the same problems in some projects, too, especially for authentication services, and solved it by scripting the bind-route-service part myself. However, having it in this resource would make it more descriptive and easier to use :)

+1

**Comment by patrickcrocker** [comment]
Command `bind-route-service` implemented in [v2.11.0](https://github.com/nulldriver/cf-cli-resource/releases/tag/v2.11.0)
