### ISSUE TITLE
command_file never recognized by `out` script

### ISSUE THREAD

**Issue by renbeynolds** [nulldriver/cf-cli-resource#48]
The out script never changes working directory to the source directory so when it checks `if [ -r "$command_file" ];` the result is always false and the parameters are not applied.

**Comment by patrickcrocker** [comment]
Thanks!!

**Comment by patrickcrocker** [comment]
Implemented in [v2.9.1](https://github.com/nulldriver/cf-cli-resource/releases/tag/v2.9.1)!
