### ISSUE TITLE
Read credentials from a file

### ISSUE THREAD

**Issue by eruvanos** [nulldriver/cf-cli-resource#59]
Hi,
our organisation just changed the access to CF and restricted CI/CD pipelines to use temporary cf users.

We are able to retrieve them in a task, but do not see a way to fill them back into the cf-cli-resource.

It would be nice, if we could provide the credentials or config.json from outside. This may also help others, that are limited to multi factor authentication using cf login --sso.

What do you think?

**Comment by aegershman** [comment]
Apologies for unwarranted interjection, but I'm curious how this could solve the `cf login --sso` use-case? What credentials would you pass in for this? Interesting.

Could see this as valuable, though some food for thought-- 

- Have you (or your org) considered using credhub/vault/etc. integration for Concourse && having some sort of automation which auto-rotates the credentials for temporary cf users by updating the credhub reference?
- If using a credentials file, would the credentials be stored unencrypted in a flat file? Do you store them in git?

Again apologies for unwarranted comments, but find this interesting.

**Comment by eruvanos** [comment]
Hi,
our platform provides a service (secured by oauth) which can create a temporary CF user using an API.

So in a task, we are calling this API and login into CF with the temporary user. We could now pass the `~/.cf/config.json` file to the next tasks or resources in the same job. The `config.json` contains the refresh token and all information to skip the login in all other tasks.

Solving the `cf login --sso` would look the same:
1. Create a task, which automates the login (for example with a python script)
2. Passing the `config.json` to the next tasks (in the same job, so they are not stored permanently)
3. Instead of `cf login --sso` copy the `config.json` to `~/.cf/config.json` (which has to be supported in resources)

PS. We are thinking about the autorotation, that could be another way to solve it.

**Comment by shyamz-22** [comment]
Hi, We are also interested in this option. We would like to know your opinion on this.  

Thanks

**Comment by patrickcrocker** [comment]
Implemented in [v2.16.0](https://github.com/nulldriver/cf-cli-resource/releases/tag/v2.16.0)
