### ISSUE TITLE
Add autoscaling functionality

### ISSUE THREAD

**Issue by SDiamante13** [nulldriver/cf-cli-resource#67]
The App Autoscaler CLI can supply autoscaling configuration to apps running in PCF through a manifest or separate commands. It was be nice to be able to set the autoscaling and toggle it through this resource. My use case is after a blue-green deployment my team wants to apply autoscaling on the new instance since its previous autoscaling setting have been wiped clean. We could have an additional task afterwards that could set the autoscaling based on a manifest. Resources: [App Autoscaler CLI](https://docs.run.pivotal.io/appsman-services/autoscaler/using-autoscaler-cli.html) & [Download Link](https://network.pivotal.io/products/pcf-app-autoscaler)

**Comment by patrickcrocker** [comment]
Thanks for the feature request.  I'll look at implementing this in a future release!

**Comment by patrickcrocker** [comment]
Unfortunately, I'm unable to package the Pivotal App Autoscaler CLI Plugin due to licensing restrictions (it's not open-source).  The autoscaler is also specific to Pivotal Cloud Foundry and not available in the open-source Cloud Foundry.
