### ISSUE TITLE
create-service doesn't allow to select service broker

### ISSUE THREAD

**Issue by roDew** [nulldriver/cf-cli-resource#68]
I had a problem trying to create a service when I have 2 of them with the same name in my marketplace. 
In my case, I have 2 Redis both with name "redis" but from different brokers, then, when I'm trying to create a service just by service name, I cannot select which one I need and I got this error:

`Creating service instance my-redis-service in org my_org / space my_space as my_user...
Service 'redis' is provided by multiple service brokers. Specify a broker by using the '-b' flag.
`
By command, I can select the broker with the -b option, but it seems this resource does not support that option.

**Comment by patrickcrocker** [comment]
Thanks for reporting this.  I see that the `-b` flag was implemented in [cli v6.43.0](https://github.com/cloudfoundry/cli/releases/tag/v6.43.0).  I'll add this in a future release soon.

**Comment by patrickcrocker** [comment]
Implemented in [v2.17.0](https://github.com/nulldriver/cf-cli-resource/releases/tag/v2.17.0)!
