### ISSUE TITLE
unknown field "params"

### ISSUE THREAD

**Issue by JuanFCabrera** [nulldriver/cf-cli-resource#70]
when using enable feature flag:  fly returns "malformed config: error unmarshaling JSON: while decoding JSON: json: unknown field "params"" 

  - put: cf-enable-feature-flag
    resource: cf-env
    params:
      command: enable-feature-flag
      feature_name: service_instance_sharing

**Comment by patrickcrocker** [comment]
Please check the spacing in your yaml (ensure you are indenting with 2 spaces properly):

**Comment by JuanFCabrera** [comment]
thank you. looks like my editor was eliminating spaces
