### ISSUE TITLE
Support for vars and vars_file in Zero Downtime Push

### ISSUE THREAD

**Issue by shyamz-22** [nulldriver/cf-cli-resource#80]
Currently Zero Down time push does not support vars and vars_file options. I think this option was not enabled due to the limitation of the AutoPilot Plugin. As this is fixed currently may be we can add the support for vars and vars_file in ZDT command

**Comment by patrickcrocker** [comment]
Implemented in [v2.19.0](https://github.com/nulldriver/cf-cli-resource/releases/tag/v2.19.0)
