### ISSUE TITLE
Can not login with v6.52.0 using $CF_HOME/.cf/config.json

### ISSUE THREAD

**Issue by elgohr** [nulldriver/cf-cli-resource#85]
Please don't upgrade to latest CF Cli for now.
See https://github.com/cloudfoundry/cli/issues/2035

At the moment this resource is using 6.51.0 (https://github.com/nulldriver/cf-cli-resource/blob/master/Dockerfile#L10), so everything is fine.

**Comment by patrickcrocker** [comment]
Interesting... the only likely impact this has on the cf-cli-resource is if you are using the [CF_HOME](https://github.com/nulldriver/cf-cli-resource#cf_home) functionality.  Is that the case for you?

**Comment by JenGoldstrich** [comment]
Worth noting that this will only be a one time breakage, once you re-log in once on v6.52.0 this will not keep happening :)!

**Comment by elgohr** [comment]
Nevertheless, we have a resource providing credentials to this resource. In this way they have to be in version-sync.
@patrickcrocker when do you plan to update to 6.52.0?

**Comment by patrickcrocker** [comment]
@elgohr please note that the next version of `cf-cli-resource` (v2.24.0) will bump the versions of the `cf` cli to v6.53.0 and v7.2.0 (to be released early at the end of this week).

I recommend that you pin to the current version (v2.23.0) in your pipeline to avoid any interruptions in your pipeline until you can update/test with the updated version.

**Comment by elgohr** [comment]
Thank you for mentioning 🙂

**Comment by patrickcrocker** [comment]
Updated to cf v6.53.0 in cf-cli-resource [v2.24.0](https://github.com/nulldriver/cf-cli-resource/releases/tag/v2.24.0)
