### ISSUE TITLE
Extend push to allow "only once"

### ISSUE THREAD

**Issue by daschaa** [nulldriver/cf-cli-resource#93]
It would be nice to configure the `push` command in a way that it can be ensured that an application is only pushed once the first time. Any "redeploy" would skip the push of the application.

Would this be possible?

**Comment by patrickcrocker** [comment]
Can you share some more details on this use case?

- In what scenario would you not want your application redeployed?
- How would you determine if an application was previously pushed?  Just query the cloud controller to see if the app already exists?

**Comment by joxw1** [comment]
First thanks for your quick response!

The use case we face is, that in one of our projects we deploy different services for every feature branch we develop. The services are needed for testing the feature manually.
If we have many code iterations, we have to often redeploy the feature which leads to "fresh" deploy all the services. However, some services should only be deployed once initially and then reused for each code redeploy.

In order not to solve this too cumbersome it would be cool if there would be a flag for the push command, which checks if the service has already been deployed. I could imagine it could be solved with a check like `cf apps xyz || cf push xzy`.

I hope the information helps and I'm looking forward for a response.

Thank you very much!
