### ISSUE TITLE
Older cf cli used in official "release"

### ISSUE THREAD

**Issue by thelangley** [nulldriver/cf-cli-resource#94]
Not really an issue but could you please cut a new release which includes new cf cli

I see Dockerfile on master has been updated which hot new clients but no releases.

**Comment by patrickcrocker** [comment]
Updated to cf cli v6.53.0 and v7.4.0 in cf-cli-resource [v2.24.0](https://github.com/nulldriver/cf-cli-resource/releases/tag/v2.24.0)

**Comment by thelangley** [comment]
that's super. Thanks for your time Patrick
