### ISSUE TITLE
Docker image tag 'latest' is not the same as 2.24.0

### ISSUE THREAD

**Issue by pjboirleaud** [nulldriver/cf-cli-resource#97]
Hello,

The latest version is not the same as your last "versionned" tag, i.e. the 2.24.0.

Maybe there's a missing release, ...a 2.25.0 ?. 

Could you please tag the latest ?

(We would need a tag instead of latest to avoid possible regressions, and your "latest" fixes a bug we face in 2.24.0 ;))

Thanks
Pierre-Jean

**Comment by patrickcrocker** [comment]
Can you expand on "the latest version is not the same as ... 2.24.0"?  What are you seeing that leads you to believe that?

**Comment by pjboirleaud** [comment]
Sure. 

Here more detailed explanations: 

When we use the 2.24.0 we have the following bug: impossibility to perform a cf push with an inline manifest, it considers the manifest content as the file name, so it fails. 

Example of output: 
[ERROR] The specified manifest does not exist: {
  "applications": [
    {
      "health-check-type": "process",
      "instances": 0,
      "memory": "1024M",
      "name": "my-app",
      "no-route": true,
      "services": [
        "my-service"
      ]
    }
  ]
}

But when we use the latest we're fine, no bug at all. 

We got the confirmation simply visiting docker hub https://hub.docker.com/r/nulldriver/cf-cli-resource/tags:
"latest" and "2.24.0" don't have the same digest

**Comment by patrickcrocker** [comment]
OK, this seems to be related to issue #95 which I thought I had manually fixed. I did a fresh `docker pull nulldriver/cf-cli-resource:2.24.0` on my local machine and verify that image has the right 2.24.0 code.  Possible that your (and other's) Concourse server cached the incorrect 2.23.0 version?

I've gone ahead and published `v2.24.1` using the fixed pipeline.  Looking at Docker hub, it looks like `latest`, `2`, `2.4`, and `2.4.1` all have the same digest as expected.  Please test and let me know!

**Comment by pjboirleaud** [comment]
Hey - many thanks for your reply
"Possible that your (and other's) Concourse server cached the incorrect 2.23.0 version?" >>> I don't think so, but not 100% sure. 
I'm gona check today the v2.24.1
I'll go back to you ASAP

**Comment by pjboirleaud** [comment]
Hello, everything is fine, now with the new versions (we've just tested the 2.24.1). 
And BTW, good idea for the tags "2", "2.24" ;)
Many thanks
PJ

**Comment by patrickcrocker** [comment]
Excellent, great to hear.

Yeah, the `2` and `2.24` tags are a nice benefit from the [pipeline fix](https://github.com/nulldriver/cf-cli-resource/commit/847cf93c7d44e6f4febae2cfe5d8f65a2bdfde37).
