### ISSUE TITLE
Feature request: cf8 

### ISSUE THREAD

**Issue by Hmarionx** [nulldriver/cf-cli-resource#99]
Hello, any roadmap for adding new cf8 cli ?

**Comment by patrickcrocker** [comment]
I've hit a roadblock where the cf8 `update-user-provided-service` command is not actually updating the service instance. I've tried 8.0.0 through 8.3.0...

I'm going to try updating my Cloud Foundry to the latest version to see if it's an issue in CF itself.  If it still doesn't work, I'll open an issue with the cf cli team.

**Comment by patrickcrocker** [comment]
OK I updated to a newer version of Cloud Foundry and the blocking issue magically went away #shinyNewVersionFTW

I've added v8 tests to the pipeline and everything is passing now.  I'm now working on adding the cf cli `v8` features (such as `--wait` on commands such as `create-service`, `bind-service`, etc.)

New release coming soon...!

**Comment by Hmarionx** [comment]
Thanks for this good news !

**Comment by patrickcrocker** [comment]
Implemented in [v2.26.0](https://github.com/nulldriver/cf-cli-resource/releases/tag/v2.26.0)!
